# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Zip build
      run: zip -r dir1.zip . 
    - name: Post aijiami scan
      run: curl --location --request POST 'http://babf82bc2c95.ngrok.io/test2021' \
            --form 'auth="4c979443a1d4ff56205487945dbb812a"' \
            --form 'langType="JAVA"' \
            --form 'projectId="wyc_test_helloworld4"' \
            --form 'projectLevel="default"' \
            --form 'feedbackUrl="http://10.253.84.6:30019/codesafe/feedbackurl"' \
            --form 'otherMessage="uuid_wyc"' \
            --form 'projectGroupId=""' \
            --form 'passLevel="1"'
#       curl --location --request POST 'http://babf82bc2c95.ngrok.io/test2021'
#       run:   curl --location --request POST 'http://babf82bc2c95.ngrok.io/test2021' \
#               --form 'auth=4c979443a1d4ff56205487945dbb812a' \
#               --form 'uploadFile=@/dir1.zip' \
#               --form 'langType=JAVA' \
#               --form 'projectId=wyc_test_helloworld4' \
#               --form 'projectLevel=default' \
#               --form 'feedbackUrl=http://10.253.84.6:30019/codesafe/feedbackurl' \
#               --form 'otherMessage=uuid_wyc' \
#               --form 'projectGroupId=' \
#               --form 'passLevel=1'
#     - name: Remove zip file
